[package]
name = "mmv"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "mmv"
path = "src/main.rs"

[lib]
name = "mmv_lib"
path = "src/lib.rs"



# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "*"
scan_dir = "*"
clap = "*"
