on: [push, workflow_dispatch]
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - uses: getsentry/action-github-app-token@v2
        id: app-token
        with:
          app_id: ${{ vars.CURIC_APP_ID }}
          private_key: ${{ secrets.CURIC_PRIVATE_KEY }}
      - name: List forks
        run: |
          forks=$(curl -L \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
            https://api.github.com/repos/rust-hse/rust-hse-2023/forks)

          forks=$(echo $forks | jq -r '.[] | .name')
          echo "Found forks:"
          echo $forks

          # Iterate over forks and start sync processes
          while IFS= read -r repo; do
            echo "Syncing $repo"
            curl -L -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" \
              https://api.github.com/repos/rust-hse/$repo/merge-upstream \
              -d '{"branch":"main"}' &
          done <<< "$forks"

          # Wait for all background processes to complete and capture their exit statuses
          fail=0
          for job in $(jobs -p); do
              wait $job || let "fail+=1"
          done
          
          # Check if any background processes failed
          if [ "$fail" -ne 0 ]; then
              echo "Failed to process $fail forks"
          else
              echo "All forks synced!"
          fi
