on: [push, workflow_dispatch]
jobs:
  sync:
    runs-on: self-hosted
    steps:
      - uses: getsentry/action-github-app-token@v2
        id: app-token
        with:
          app_id: ${{ vars.CURIC_APP_ID }}
          private_key: ${{ secrets.CURIC_PRIVATE_KEY }}
      - name: List forks
        run: |
          curl -v -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.app-token.outputs.token }}" https://api.github.com/repos/rust-hse/rust-hse-2023/forks
